[package]
name = "core"
version = "0.2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
rsa = { version = "=0.9.6" }
rand = { version = "=0.8.5" }
base64 = { version = "=0.22.1" }
thiserror = { version = "1.0" }
